### PR TITLE
Use same UI-Style as other Nextcloud Android apps

### PR DESCRIPTION
**Pull request by newhinton**
This introduces a multi-screen layout. It splits the current main view into multiple fragments that can be accessed by a navigation drawer.

### CODE REVIEW

**Comment by Andrewerr** [comment]
Hello. Thank you for your contirbution! As far as I see it is not ready yet, so I am marking it as a draft.

**Comment by newhinton** [comment]
@Andrewerr I have added the basic appbar as the officals app use it. The base functionality of the app works, but most of the ui has no function at the moment. I would still like to hear feedback if that is something you can imagine merging because there is a lot of work still to do!

**Comment by Andrewerr** [comment]
> @Andrewerr I have added the basic appbar as the officals app use it. The base functionality of the app works, but most of the ui has no function at the moment. I would still like to hear feedback if that is something you can imagine merging because there is a lot of work still to do!

I like your idea to make the style of this app unified with style of other Nextcloud apps and of course when your changes would be ready I would definetely merge them. Also feel free to ask me to help if you have any issues with integrating my code with yours.

**Comment by newhinton** [comment]
@Andrewerr I think i have now progressed enough for a review. I have now updated most of the user interface.
There are still todos:
- [ ] Translations are missing in most of the app
- [ ] There are some Preferences that seemingly do not belong to this app

**Comment by Andrewerr** [comment]
@newhinton Thank you very much for your work! I will add your issue about translation as enhancment to issues list. Also could you please explain what you mean by your second todo since I do not really understand which of preferences do not belong to this app.

**Review by Andrewerr — COMMENTED** [review]
Ok, I have just finished review. There are some issues with manifests: as you have updated API level to `31` you now need to specify `android:exported="true"` for boot receiver. As per others code it looks well. 
 After launching the app there are still few bugs noticable, e.g. Status is not updated despite service is running. Also, there are some settings that seem to be an example, so I have understood about what you have been talking in you 2nd todo :)
 So if you are not planning to work anymore on this pull request I can merge it and continue improving it myself. Also if you are planning to work on it further, please cherry-pick my commit `e6aa064` which fixes CI failing to build app.

**Comment by newhinton** [comment]
I mean those two categories:
Screenshot_20220106-135814_Notifications

i may be mistaken and they do something important, but if they do, they need a better explanation or maybe even their own fragment

**Comment by Andrewerr** [comment]
This settings are from default example fragment for preference controller which are provided by android studio and so they can be safely deleted. As per floating button I have no idea how it appeared here, but I think it also can be safely removed.

**Comment by newhinton** [comment]
@Andrewerr Oh i didn't see your updated comment! I added a few commits that should help with some of the issues, but it should be able to merge just fine!

**Review by Andrewerr — APPROVED** [review]
Thank you once more for your great job! I am approivng this merge :) 
 Still you are likely to be unable to merge it yourself due to CI is failing(there was just wrong java version), so I will merege it myself now and I think CI would pass(since on `main` branch java version is already fixed)

**Comment by Andrewerr** [comment]
@newhinton I am sorry. There is some issues with translations, so have I misunderstood you and merged this PR too early?

**Comment by newhinton** [comment]
@Andrewerr not really, i just were in a good mood and just moved many strings to the appropriate file! 
The pr was good to go and i will probably continue improving it, but the changes will probably far smaller pr's
(except maybe the notification history)

**Pull request merged**
